### ISSUE TITLE
clang: error: argument unused during compilation: '-fno-eliminate-unused-debug-types'

### ISSUE THREAD

**Issue by ehmo** [djimenez/iconv-go#20]
Immediately after go get or go install. Any idea how to solve it?

**Comment by djimenez** [comment]
What os, go version, clang version are you using? and how are you telling cgo to use clang? some googling suggests that prior to 1.2 go had some issues when using clang

https://github.com/golang/go/issues/4829

If you are on a mac with homebrew based go, might want to see:

https://github.com/golang/go/issues/6544

these are both pretty old cgo issues though.

**Comment by ehmo** [comment]
You're right. I'm using go 1.2 on Mac. Should update more often. Thanks you
