### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by snipermiller** [djimenez/iconv-go#21]
C:/Go/bin/go.exe build -i [C:/Go/src/MdisDataTransform]
成功: プロセスがコード 0 で終了しました
C:/Go/src/MdisDataTransform/MdisDataTransform.exe  [C:/Go/src/MdisDataTransform]
###### #####1!

Exception 0xc0000005 0x0 0xffffffff 0x53b0b5
PC=0x53b0b5
signal arrived during cgo execution

github.com/djimenez/iconv-go._C2func_iconv_open(0x362f78, 0x362f88, 0x0, 0x0, 0x0)
    github.com/djimenez/iconv-go/_obj/_cgo_gotypes.go:46 +0x4f
github.com/djimenez/iconv-go.NewConverter(0x4d1bc8, 0x4, 0x4d1eb8, 0x5, 0x115ec190, 0x0, 0x0)
    C:/Go/src/github.com/djimenez/iconv-go/converter.go:30 +0x88
github.com/djimenez/iconv-go.NewReader(0x311bf8, 0x115ec180, 0x4d1bc8, 0x4, 0x4d1eb8, 0x5, 0x0, 0x0, 0x0)
    C:/Go/src/github.com/djimenez/iconv-go/reader.go:18 +0x50
main.main()
    C:/Go/src/MdisDataTransform/DataTransform.go:46 +0x741

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    c:/go/src/runtime/asm_386.s:2287 +0x1
eax     0x7700a5
ebx     0x115f1ccc
ecx     0x553120
edx     0x115f1c8c
edi     0x374
esi     0x54b520
ebp     0x54b740
esp     0x12fe9c
eip     0x53b0b5
eflags  0x10287
cs      0x1b
fs      0x3b
gs      0x0
# 

source:
inputFile, inputErr := os.Open("E:\TestFolder\srcData_150716.CSV")
    if inputErr != nil {
        logger.Println("input file readding error!")
        os.Exit(-1)
    }
    defer inputFile.Close()
    fmt.Println("###########1!")
    converter, convErr := iconv.NewReader(inputFile, "sjis", "utf-8")
    fmt.Println("###########2!")
    if convErr != nil {
        logger.Println("cant transform encoding from sjis to utf-8!")
        os.Exit(-1)
    }
    reader := csv.NewReader(converter)

**Comment by djimenez** [comment]
I'm not sure what's going on, but I can try to help.

Can you provide the go version? From your snippets I'm inferring windows on x86, is that right? how are you making iconv available for cgo?
