### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by scorpnode** [djimenez/iconv-go#22]
runtime error: invalid memory address or nil pointer dereference
	parser.Parse(func(toWrite string, element *goparser.HtmlElement) {
    if element.TagName == "title" {
		theTitle.WriteString(toWrite)
    }
	},nil, nil)
In /app/models/prime.go (around line 50)

45:
 // tags := make(map[string]string)
46:
  
47:
 theTitle := bytes.NewBufferString("")
48:
 
49:
	parser.Parse(func(toWrite string, element *goparser.HtmlElement) {
50:
    if element.TagName == "title" {
51:
		theTitle.WriteString(toWrite)
52:
    }
53:
	},nil, nil)
54:
fmt.Println(theTitle)
Call Stack

/root/go/src/myapp/app/models/prime.go:50 (0x67cab7)
	ParseLink.func1: if element.TagName == "title" {
/root/go/src/github.com/calbucci/go-htmlparser/htmlparser.go:186 (0x77f458)
	(*HtmlParser).callText: p.textCallback(text, parent)
/root/go/src/github.com/calbucci/go-htmlparser/htmlparser.go:268 (0x780585)
	(*HtmlParser).internalParse: hp.callText(text2, parent)
/root/go/src/github.com/calbucci/go-htmlparser/htmlparser.go:102 (0x77ed15)
	(*HtmlParser).Parse: parser.internalParse()
/root/go/src/myapp/app/models/prime.go:53 (0x67c6c6)
	ParseLink: },nil, nil)
/root/go/src/myapp/app/controllers/app.go:38 (0x4ca87c)
	App.Parse: jsonResult:=models.ParseLink(parseInfo);
<autogenerated>:21 (0x4cb64b)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45ac3e)
	call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:432 (0x470cfa)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:300 (0x46f9c1)
	Value.Call: return v.call("Call", in)
/root/work/src/github.com/revel/revel/invoker.go:36 (0x49568a)
/root/work/src/github.com/revel/revel/compress.go:47 (0x486fb2)
/root/work/src/github.com/revel/revel/intercept.go:103 (0x494362)
/root/go/src/myapp/app/init.go:37 (0x4c9cdf)
	glob.func1: fc[0](c, fc[1:]) // Execute the next filter stage.
/root/work/src/github.com/revel/revel/i18n.go:155 (0x49364c)
/root/work/src/github.com/revel/revel/validation.go:191 (0x4ac7c6)
/root/work/src/github.com/revel/revel/flash.go:46 (0x48fdd0)
/root/work/src/github.com/revel/revel/session.go:149 (0x4a7785)
/root/work/src/github.com/revel/revel/params.go:133 (0x4978ef)
/root/work/src/github.com/revel/revel/filterconfig.go:208 (0x48f94d)
/root/work/src/github.com/revel/revel/router.go:474 (0x4a485f)
/root/work/src/github.com/revel/revel/panic.go:15 (0x495ae1)
/root/work/src/github.com/revel/revel/watcher.go:232 (0x4b3536)
/root/work/src/github.com/revel/revel/server.go:50 (0x4a53fe)
/root/work/src/github.com/revel/revel/server.go:38 (0x4a4f6f)
/usr/local/go/src/net/http/server.go:1422 (0x54ad7a)
	HandlerFunc.ServeHTTP: f(w, r)
/usr/local/go/src/net/http/server.go:1862 (0x54cfee)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1361 (0x54a83e)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x45cf61)
	goexit: BYTE	$0x90	// NOP

**Comment by djimenez** [comment]
anyway you can reduce this to a test case? - the stack trace is great, but i dont' know which of this code you control and which you don't, nor the versions of the code referenced (when they're in public repots), and i have no idea what it was trying to convert / write at the time. since revel and go-html-parser don't seem to use me directly, I can only assume you've given them an iconv.Writer and something has gone wrong during that?

Finally, this was just a pet project, unless you specifically need a feature of iconv, you might consider using https://godoc.org/golang.org/x/text/encoding which is pure go rather than cgo wrapper of iconv.

**Comment by scorpnode** [comment]
Thanks for your help :)
