### ISSUE TITLE
go build error 

### ISSUE THREAD

**Issue by zhangweilun** [djimenez/iconv-go#31]
➜  proxy git:(master) CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
# github.com/zhangweilun/proxy/vendor/github.com/djimenez/iconv-go
vendor/github.com/djimenez/iconv-go/reader.go:10: undefined: Converter

I am in a Mac computer to build a binary file that can run a linux computer,but it is not work,but I can successful build on Mac system

**Comment by djimenez** [comment]
your cross compile has cgo disabled

from the project README:

> PLEASE NOTE that this package requires the use of cgo, since it is only a wrapper around iconv - either provided by libiconv or glibc on your system. Attempts to build without cgo enabled will fail.

For a pure golang package I suggest using golang.org/x/text
