### ISSUE TITLE
do you have a plan to do it with pure go?

### ISSUE THREAD

**Issue by zhangweilun** [djimenez/iconv-go#32]
I use it to crawl the web page,with your library is vary convenient to convert a charset to another chatset,but it have a boresome problem,i can not build a binary file on my Mac,i hope that will have a pure go .

**Comment by djimenez** [comment]
no, this project will never have a pure go iconv implementation - it's not its purpose. 

As I listed before, you can do pure go transcoding with golang/x/text  for example, your single usage of my library can be replaced by the following in your proxy project:

replace
```go
utf_body, err := iconv.NewReader(res.RawResponse.Body, "gbk", "utf-8")
if err != nil {
	log.Fatalln(err)
}
```
with
```go
utf_body := simplifiedchinese.GBK.NewDecoder().Reader(res.RawResponse.Body)
```
after adding the import
```golang.org/x/text/encoding/simplifiedchinese```

**Comment by zhangweilun** [comment]
thanks for your help,
