### ISSUE TITLE
iconv.h: No such file or directory

### ISSUE THREAD

**Issue by kalsolio** [djimenez/iconv-go#38]
# github.com/djimenez/iconv-go
go\src\github.com\djimenez\iconv-go\converter.go:8:19: fatal error: iconv.h: No such file or directory
compilation terminated.

**Comment by djimenez** [comment]
The package is just using cgo to use an iconv implementation on your system. An appropriate iconv has to be available and usable by the c compiler go is calling out to.

 I would suggest using https://godoc.org/golang.org/x/text/encoding (which is pure go) if you don't have a legacy reason to need to use a specific iconv implementation.
