### ISSUE TITLE
Cannot convert big5 to utf-8 

### ISSUE THREAD

**Issue by lunyi** [djimenez/iconv-go#39]
Hi Sir 

I moved code https://siongui.github.io/2018/10/09/goquery-handle-non-utf8-html-webpage/ 
to https://play.golang.org/p/RkryK4BjXHp

I ran into the error when running
github.com/djimenez/iconv-go
../gopath518902796/pkg/mod/github.com/djimenez/iconv-go@v0.0.0-20160305225143-8960e66bd3da/reader.go:10:21: undefined: Converter 

is there a solution ?

**Comment by djimenez** [comment]
go playground doesn't support cgo which is required by this package. 

I suggest you look at something like golang.org/x/text  if you don't specifically need to use libiconv or don't want to use cgo. It has a Big5 encoding https://godoc.org/golang.org/x/text/encoding/traditionalchinese

**Comment by lunyi** [comment]
> go playground doesn't support cgo which is required by this package.
> 
> I suggest you look at something like golang.org/x/text if you don't specifically need to use libiconv or don't want to use cgo. It has a Big5 encoding https://godoc.org/golang.org/x/text/encoding/traditionalchinese


I got it, thanks. 
Here use ioutil and traditionalchinese.Big5.NewDecoder()

func newDocumentFromNonUtf8Url(url string, charset string) (doc *goquery.Document, err error) {
	resp, err := http.Get(url)
	if err != nil {
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Printf("get content failed status code is %d. \n", resp.StatusCode)
		return
	}
	BodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Println("HTML body read error.")
		return
	}
	decodeStr, _ := decodeBig5([]byte(BodyBytes))
	doc, err = goquery.NewDocumentFromReader(bytes.NewReader(decodeStr))
	return
}


func decodeBig5(s []byte) ([]byte, error) {
	I := bytes.NewReader(s)
	O := transform.NewReader(I, traditionalchinese.Big5.NewDecoder())
	d, e := ioutil.ReadAll(O)
	if e != nil {
		return nil, e
	}
	return d, nil
}
